### ISSUE TITLE
Copy the CI tooling from the RFC repo

### ISSUE THREAD

**Issue by bkchr** [polkadot-fellows/xcm-format#62]
I think we want to have the same automation as on the RFC repo? If yes, we can just copy it from there.

@rzadp are you interested in helping with this?

**Comment by rzadp** [comment]
> @rzadp are you interested in helping with this?

Sure, I'll try to help. Is the process analogical to the RFC one - voting on a remark in the collectives parachain?

BTW, did you see [this one](https://github.com/polkadot-fellows/Evidences/pull/17)?

**Comment by acatangiu** [comment]
hmm, I was thinking to _join_ the xcm RFC process with the general RFC repo - aka, drop this XCM-specific RFC and use the one in https://github.com/polkadot-fellows/RFCs

This repo would only hold the spec.

**Comment by bkchr** [comment]
> hmm, I was thinking to _join_ the xcm RFC process with the general RFC repo - aka, drop this XCM-specific RFC and use the one in https://github.com/polkadot-fellows/RFCs

Ahh fine as well! How did you imagined the merge rights for this repo?

**Comment by bkchr** [comment]
> BTW, did you see [this one](https://github.com/polkadot-fellows/Evidences/pull/17)?

Yeah I have seen this one. We can probably merge it, but the future move to use subsquare/polkassembly directly will probably render it useless.

**Comment by bkchr** [comment]
Sounds fine to me. I think at some point someone proposed to directly modify the spec. This would merge the RFC with modifying the spec. However, it may makes it more complicated to review the actual changes.

**Comment by franciscoaguirre** [comment]
The RFCs make it better to review the actual changes, I'd put them in the already existing process and then update the spec

**Comment by acatangiu** [comment]
> use the same merge rights for https://github.com/polkadot-fellows/xcm-format as for https://github.com/polkadot-fellows/runtimes and we can reuse the process and automation/scripts from there

@rzadp @alvicsam @bullrich who can help with this?

**Comment by rzadp** [comment]
The point of re-using the `polkadot-fellows/RFCs` for these XCM RFCs makes total sense to me.
But I have some questions about what happens next. I didn't have much to do with XCM so might be missing something.

---

@acatangiu If we want to use same access rights, automations, etc as `polkadot-fellows/runtimes` here in `polkadot-fellows/xcm-format`, then why don't we place the XCM format into the `runtimes` repo?
Since it's the same owner, same group responsible, and Polkadot&Kusama are supposed to be implementing it.

This `xcm-format` repo could be a read-only automated copy, if need be.

If we seperate the "staging" XCM spec from the one that is currently implemented in Polkadot/Kusama, we would have the advantage of easily correlating the XCM format that is the basis of any given release (or any given commit) in the `runtimes` repo.
Right now, if I look at any old release of Polkadot/Kusama, do I have a way of finding the exact version of XCM format used to implement it? Other than browsing timestamps.

---

So I would propose the following modified steps:

0. An `xcm-format.md` file exists in `runtimes`, and the implementation in the repo is based on it.
1. **[no changes]** someone proposes RFC to https://github.com/polkadot-fellows/RFCs, RFC is approved and merged (using the process there)
2. someone (else) opens PR to https://github.com/polkadot-fellows/runtimes for updating spec based on approved RFC - creating a new `xcm-format-pending.md`
3. someone (else) opens PR for updating implementation in https://github.com/polkadot-fellows/runtimes based on the approved RFC and pending spec. In the same PR, `mv xcm-format-pending.md > xcm-format.md` is done.

What do you all think? Of course it falls apart if the XCM format MUST be detached from the `runtimes`.

**Comment by acatangiu** [comment]
> then why don't we place the XCM format into the runtimes repo?

The XCM specification and the system chain runtimes are totally different things. It just happens that the `fellowship` is responsible for maintaining both. That's why they both live under the `polkadot-fellows` GH organization.

The [Polkadot Protocol spec](https://spec.polkadot.network/id-polkadot-protocol) is also under the purview of the fellowship, but it is, same as XCM, larger scope than system chain runtimes so they're not lumped together.

As such, I would not move the spec under https://github.com/polkadot-fellows/runtimes, it deserves its own repo with its own audience (albeit same maintainers as the `runtimes` repo).

(Also, a clarification missing from my original post: Actually the XCM spec is also not really implemented in https://github.com/polkadot-fellows/runtimes, but in https://github.com/paritytech/polkadot-sdk, and eventually integrated into https://github.com/polkadot-fellows/runtimes)

**Comment by rzadp** [comment]
Ok, fair enough.

So my takeaway is that:

1. We do NOT want to copy the CI tooling from the RFC repo - but rather move with the xcm RFCs over there.
2. We want to duplicate the merging rights/automations in this `xcm-format` repository from `runtimes` - mainly we're talking about the [review-bot](https://github.com/paritytech/review-bot/), if I understand correctly.

**Comment by acatangiu** [comment]
@rzadp yes, correct!

1. will be handled by the RFC authors - they will have to migrate their RFCs from here to https://github.com/polkadot-fellows/RFCs
2. this is where we need help from you 🙏

**Comment by Bullrich** [comment]
I created a ticket:
- https://github.com/polkadot-fellows/RFCs/issues/95

Once this is completed, I can install Review-Bot.
